name: custom_form_builder
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  bloc: ^8.1.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0

dev_dependencies:
  build_runner: ^2.3.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  json_serializable: ^6.5.1

flutter:
  uses-material-design: true
